[mcp_servers.espressif-documentation]
url = "https://mcp.espressif.com/docs"
enabled = true
required = false
default_tools_approval_mode = "writes"
startup_timeout_sec = 20
tool_timeout_sec = 60

[mcp_servers.esp-component-registry]
url = "https://components.espressif.com/mcp"
enabled = true
required = false
default_tools_approval_mode = "writes"
startup_timeout_sec = 20
tool_timeout_sec = 60

[mcp_servers.espressif-engineering]
url = "https://ts-mcp.espressif.com/mcp"
enabled = true
required = false
default_tools_approval_mode = "prompt"
startup_timeout_sec = 20
tool_timeout_sec = 90
