#include "config_core.h"
#include <algorithm>
#include <cctype>
#include <cstring>
#include <string>
namespace deskmate::easyinput { namespace {
uint16_t u16(const uint8_t*p){return static_cast<uint16_t>(p[0]|(p[1]<<8));} uint32_t u32(const uint8_t*p){return p[0]|(p[1]<<8u)|(p[2]<<16u)|(p[3]<<24u);} void w16(uint8_t*p,uint16_t v){p[0]=v;p[1]=v>>8;} void w32(uint8_t*p,uint32_t v){p[0]=v;p[1]=v>>8;p[2]=v>>16;p[3]=v>>24;}
std::string compact(std::string_view s){std::string o;bool q=false,e=false;for(char c:s){if(!q&&std::isspace((unsigned char)c))continue;o+=c;if(q&&e)e=false;else if(q&&c=='\\')e=true;else if(c=='"')q=!q;}return o;}
bool val(const std::string&j,const std::string&k,std::string&o,size_t st=0){auto n="\""+k+"\":";auto p=j.find(n,st);if(p==std::string::npos)return false;p+=n.size();auto b=p;if(p>=j.size())return false;if(j[p]=='"'){bool e=false;for(++p;p<j.size();++p){if(e)e=false;else if(j[p]=='\\')e=true;else if(j[p]=='"'){o=j.substr(b,p-b+1);return true;}}return false;}if(j[p]=='{'||j[p]=='['){char op=j[p],cl=op=='{'?'}':']';int d=0;bool q=false,e=false;for(;p<j.size();++p){char c=j[p];if(q){if(e)e=false;else if(c=='\\')e=true;else if(c=='"')q=false;}else if(c=='"')q=true;else if(c==op)++d;else if(c==cl&&--d==0){o=j.substr(b,p-b+1);return true;}}return false;}while(p<j.size()&&j[p]!=','&&j[p]!='}'&&j[p]!=']')++p;o=j.substr(b,p-b);return !o.empty();}
bool unq(const std::string&v,std::string&o){if(v.size()<2||v.front()!='"'||v.back()!='"')return false;o.clear();for(size_t i=1;i+1<v.size();++i){if(v[i]=='\\'){if(++i+1>=v.size())return false;char c=v[i];if(c!='"'&&c!='\\'&&c!='/')return false;o+=c;}else{o+=v[i];}}return true;}
bool action(const std::string&v,ConfigAction&a){std::string n;if(unq(v,n)){if(n=="disabled")a.kind=ConfigActionKind::Disabled;else if(n=="voice_ptt_hold")a.kind=ConfigActionKind::VoiceInput;else if(n=="edit_ptt_hold")a.kind=ConfigActionKind::VoiceEdit;else if(n=="select_all")a={ConfigActionKind::SelectAll,1,4};else if(n=="copy")a={ConfigActionKind::Copy,1,6};else if(n=="paste")a={ConfigActionKind::Paste,1,25};else if(n=="undo")a={ConfigActionKind::Undo,1,29};else a.kind=ConfigActionKind::Unsupported;return true;}std::string h;if(!val(v,"hotkey",h))return false;std::string s;if(!unq(h,s)||s.empty()||s.size()>64)return false;uint8_t m=0,u=0;size_t b=0;while(b<=s.size()){auto e=s.find('+',b);auto t=s.substr(b,e==std::string::npos?e:e-b);if(t=="Ctrl"||t=="Control")m|=1;else if(t=="Shift")m|=2;else if(t=="Alt"||t=="Option")m|=4;else if(t=="Meta"||t=="Command")m|=8;else if(t=="Return"||t=="Enter")u=0x28;else if(t=="Backspace")u=0x2a;else if(t=="Space")u=0x2c;else if(t.size()==1&&std::isalpha((unsigned char)t[0]))u=static_cast<uint8_t>(4+std::toupper(t[0])-'A');else return false;if(e==std::string::npos)break;b=e+1;}if(!m&&!u)return false;a={ConfigActionKind::Hotkey,m,u};return true;}
}
uint16_t config_crc16_ccitt(const uint8_t*d,size_t n){uint16_t c=0xffff;for(size_t i=0;i<n;++i){c^=static_cast<uint16_t>(d[i])<<8;for(int b=0;b<8;++b)c=(c&0x8000)?static_cast<uint16_t>((c<<1)^0x1021):static_cast<uint16_t>(c<<1);}return c;}
ConfigReceiveStatus ConfigWriteAssembler::accept(const uint8_t*p,size_t n,uint32_t ep){if(!p||n<11||p[0]!='S'||p[1]!='3'||p[2]!='C'||p[3]!=1)return ConfigReceiveStatus::Rejected;const uint8_t i=p[4],t=p[5],z=p[8];const uint16_t l=u16(p+6),c=u16(p+9);if(!t||t>40||!l||l>kConfigMaxJsonBytes||!z||z>kConfigWriteChunkBytes||i>=t||11u+z>n){abort();return ConfigReceiveStatus::Rejected;}if(i==0){abort();active_=true;epoch_=ep;total_chunks_=t;declared_length_=l;declared_crc_=c;}if(!active_||ep!=epoch_||i!=expected_chunk_||t!=total_chunks_||l!=declared_length_||c!=declared_crc_||static_cast<size_t>(i)*kConfigWriteChunkBytes+z>l){abort();return ConfigReceiveStatus::Rejected;}std::copy_n(p+11,z,document_.bytes.begin()+i*kConfigWriteChunkBytes);++expected_chunk_;if(expected_chunk_!=total_chunks_)return ConfigReceiveStatus::Accepted;document_.length=l;document_.crc16=c;bool exact=static_cast<size_t>(t-1)*kConfigWriteChunkBytes+z==l;bool good=exact&&config_crc16_ccitt(document_.bytes.data(),l)==c;active_=false;return good?ConfigReceiveStatus::Complete:ConfigReceiveStatus::Rejected;}
void ConfigWriteAssembler::abort(){document_={};epoch_=0;expected_chunk_=total_chunks_=0;declared_length_=declared_crc_=0;active_=false;}
bool decode_config_read_request(const uint8_t*p,size_t n,ConfigReadRequest&o){if(!p||n!=16||p[0]!='S'||p[1]!='3'||p[2]!='R'||p[3]!=1||p[8]!=2)return false;auto id=u32(p+4);if(!id||std::any_of(p+9,p+16,[](uint8_t v){return v!=0;}))return false;o.request_id=id;return true;}
bool ConfigReadStream::replace(uint32_t id,const ConfigDocument&d,uint32_t ep){abort();if(!id||!d.length||d.length>kConfigMaxJsonBytes||config_crc16_ccitt(d.bytes.data(),d.length)!=d.crc16)return false;document_=d;request_id_=id;epoch_=ep;total_chunks_=static_cast<uint8_t>((d.length+kConfigReadChunkBytes-1)/kConfigReadChunkBytes);pending_=true;return true;}
bool ConfigReadStream::encode_next(std::array<uint8_t,kConfigFeaturePayloadBytes>&o)const{if(!pending_)return false;o={};auto off=static_cast<size_t>(next_chunk_)*kConfigReadChunkBytes;auto count=std::min(kConfigReadChunkBytes,static_cast<size_t>(document_.length)-off);o[0]=6;o[1]=next_chunk_;o[2]=total_chunks_;o[3]=static_cast<uint8_t>(10+count);o[4]=1;w32(o.data()+5,request_id_);w16(o.data()+9,document_.length);w16(o.data()+11,document_.crc16);o[13]=static_cast<uint8_t>(document_.source);std::copy_n(document_.bytes.data()+off,count,o.begin()+14);return true;}
bool ConfigReadStream::mark_sent(){if(!pending_)return false;if(++next_chunk_>=total_chunks_)pending_=false;return !pending_;} void ConfigReadStream::abort(){document_={};request_id_=epoch_=0;next_chunk_=total_chunks_=0;pending_=false;}
bool parse_config_projection(std::string_view raw,ConfigProjection&o){if(raw.empty()||raw.size()>kConfigMaxJsonBytes)return false;auto j=compact(raw);std::string v;if(!val(j,"schema",v)||v!="\"ai_keyboard.v1\"")return false;if(!val(j,"profiles",v)||v.size()<4||v[0]!='['||v[1]!='{')return false;auto p=v.substr(1,v.size()-2);std::string keys;if(!val(p,"keys",keys))return false;ConfigProjection x{};for(size_t i=0;i<8;++i){std::string b,a;if(!val(keys,"KEY"+std::to_string(i+1),b)||!val(b,"press",a)||!action(a,x.keys[i]))return false;}std::string enc;if(!val(p,"encoder",enc))return false;std::string a;if(!val(enc,"press",a)||!action(a,x.encoder_press))return false;std::string s;if(val(enc,"scroll",s)){if(val(s,"mode",v))x.encoder_cursor=v=="\"cursor\"";if(val(s,"axis",v))x.encoder_horizontal=v=="\"horizontal\"";if(val(s,"speed",v)){int z=std::stoi(v);if(z<1||z>5)return false;x.encoder_speed=static_cast<uint8_t>(z);}if(val(s,"windows_reverse_vertical",v))x.reverse_vertical=v=="true";if(val(s,"windows_reverse_horizontal",v))x.reverse_horizontal=v=="true";}o=x;return true;}
const char* compiled_safe_config_json(){return R"({"schema":"ai_keyboard.v1","target_platform":"windows","profiles":[{"id":"default","keys":{"KEY1":{"press":"voice_ptt_hold"},"KEY2":{"press":{"hotkey":"Return"}},"KEY3":{"press":"edit_ptt_hold"},"KEY4":{"press":{"hotkey":"Backspace"}},"KEY5":{"press":"select_all"},"KEY6":{"press":"copy"},"KEY7":{"press":"paste"},"KEY8":{"press":"undo"}},"encoder":{"left":"disabled","right":"disabled","press":"disabled","scroll":{"enabled":true,"mode":"scroll","axis":"vertical","speed":3,"windows_reverse_vertical":false,"windows_reverse_horizontal":false}}}]})";}
bool validate_config_record(const ConfigSlotRecord&r){ConfigProjection p{};return r.magic==kConfigRecordMagic&&r.version==kConfigRecordVersion&&r.length&&r.length<=kConfigMaxJsonBytes&&config_crc16_ccitt(r.bytes.data(),r.length)==r.crc16&&parse_config_projection({reinterpret_cast<const char*>(r.bytes.data()),r.length},p);}
ConfigLoadResult select_config_record(const ConfigSlotRecord*a,const ConfigSlotRecord*b,ConfigSlot m){bool va=a&&validate_config_record(*a),vb=b&&validate_config_record(*b);const ConfigSlotRecord*s=nullptr;ConfigSlot sl=ConfigSlot::Invalid;bool rec=false;if(m==ConfigSlot::A&&va){s=a;sl=ConfigSlot::A;}else if(m==ConfigSlot::B&&vb){s=b;sl=ConfigSlot::B;}else{rec=va||vb;if(va&&(!vb||a->generation>=b->generation)){s=a;sl=ConfigSlot::A;}else if(vb){s=b;sl=ConfigSlot::B;}}ConfigLoadResult r{};r.slot=sl;r.recovered_marker=rec;if(s){r.document.length=s->length;r.document.crc16=s->crc16;r.document.source=ConfigSource::DeskMate;std::copy_n(s->bytes.begin(),s->length,r.document.bytes.begin());r.generation=s->generation;}return r;}
ConfigSaveStatus save_config_transaction(ConfigStorageBackend&b,const ConfigDocument&d,ConfigSlot a,uint32_t g){ConfigProjection p{};if(!parse_config_projection(d.view(),p)||config_crc16_ccitt(d.bytes.data(),d.length)!=d.crc16)return ConfigSaveStatus::WriteFailed;auto in=a==ConfigSlot::A?ConfigSlot::B:ConfigSlot::A;ConfigSlotRecord r{};r.length=d.length;r.generation=g+1;r.crc16=d.crc16;std::copy_n(d.bytes.begin(),d.length,r.bytes.begin());if(!b.write_slot(in,r))return ConfigSaveStatus::WriteFailed;if(!b.commit())return ConfigSaveStatus::CommitFailed;ConfigSlotRecord rb{};if(!b.read_slot(in,rb)||std::memcmp(&r,&rb,sizeof(r))!=0||!validate_config_record(rb))return ConfigSaveStatus::ReadbackFailed;if(!b.write_marker(in)||!b.commit())return ConfigSaveStatus::MarkerFailed;return ConfigSaveStatus::Saved;}
}
