const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopBridge", {
  getCapabilities: () => ipcRenderer.invoke("desktop:get-capabilities"),
  refreshLinkDiagnostics: () => ipcRenderer.invoke("desktop:refresh-link-diagnostics"),
  getManualCalibrationStatus: () => ipcRenderer.invoke("desktop:get-manual-calibration-status"),
  queryManualCalibration: () => ipcRenderer.invoke("desktop:query-manual-calibration"),
  sendManualCalibrationCommand: (value) => ipcRenderer.invoke("desktop:send-manual-calibration-command", value),
  onManualCalibrationStatus: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("manual-calibration-status", handler); return () => ipcRenderer.removeListener("manual-calibration-status", handler); },
  getNetworkSummary: () => ipcRenderer.invoke("desktop:get-network-summary"),
  getEasyInputAudioStatus: () => ipcRenderer.invoke("desktop:get-easyinput-audio-status"),
  openEasyInputAudioSetup: () => ipcRenderer.invoke("desktop:open-easyinput-audio-setup"),
  startEasyInputMicTest: () => ipcRenderer.invoke("desktop:start-easyinput-mic-test"),
  stopEasyInputMicTest: () => ipcRenderer.invoke("desktop:stop-easyinput-mic-test"),
  onEasyInputAudioEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("easyinput-audio-event", handler); return () => ipcRenderer.removeListener("easyinput-audio-event", handler); },
  startEasyInputVoiceRecording: () => ipcRenderer.invoke("desktop:start-easyinput-voice-recording"),
  stopEasyInputVoiceRecording: () => ipcRenderer.invoke("desktop:stop-easyinput-voice-recording"),
  cancelEasyInputVoiceRecording: () => ipcRenderer.invoke("desktop:cancel-easyinput-voice-recording"),
  onEasyInputVoiceRecordingEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("easyinput-voice-recording-event", handler); return () => ipcRenderer.removeListener("easyinput-voice-recording-event", handler); },
  registerShortcut: (shortcut) => ipcRenderer.invoke("desktop:register-shortcut", shortcut),
  setGlobalShortcutsEnabled: (enabled) => ipcRenderer.invoke("desktop:set-global-shortcuts-enabled", Boolean(enabled)),
  setShortcutCapture: (active) => ipcRenderer.invoke("desktop:set-shortcut-capture", Boolean(active)),
  listApplications: () => ipcRenderer.invoke("desktop:list-applications"),
  registerApplication: (token) => ipcRenderer.invoke("desktop:register-application", token),
  chooseApplication: () => ipcRenderer.invoke("desktop:choose-application"),
  testApplication: (id) => ipcRenderer.invoke("desktop:test-application", id),
  readKeyboardConfig: () => ipcRenderer.invoke("desktop:read-keyboard-config"),
  previewKeyboardConfigPatch: (patch) => ipcRenderer.invoke("desktop:preview-keyboard-config-patch", patch),
  commitKeyboardConfig: (token) => ipcRenderer.invoke("desktop:commit-keyboard-config", token),
  setTriggerConfig: (value) => ipcRenderer.invoke("desktop:set-trigger-config", value),
  setVoiceRecording: (recording) => ipcRenderer.invoke("desktop:set-voice-recording", Boolean(recording)),
  setVoiceState: (value) => ipcRenderer.invoke("desktop:set-voice-state", value),
  setManualAgentState: (value) => ipcRenderer.invoke("desktop:set-manual-agent-state", value),
  setActiveAgentProvider: (provider) => ipcRenderer.invoke("desktop:set-active-agent-provider", provider),
  getAgentProviderStatus: (provider) => ipcRenderer.invoke("desktop:get-agent-provider-status", provider),
  getCodexAgentStatus: () => ipcRenderer.invoke("desktop:get-codex-agent-status"),
  writeClipboard: (text) => ipcRenderer.invoke("desktop:clipboard-write", text),
  pasteActiveWindow: (text) => ipcRenderer.invoke("desktop:paste-active-window", text),
  keyDiagnostic: (event) => ipcRenderer.invoke("desktop:key-diagnostic", event),
  getBailianStatus: () => ipcRenderer.invoke("bailian:get-status"),
  saveBailianCredentials: (value) => ipcRenderer.invoke("bailian:save-credentials", value),
  clearBailianCredentials: () => ipcRenderer.invoke("bailian:clear-credentials"),
  getAiServiceStatus: () => ipcRenderer.invoke("ai-services:get-status"),
  saveTextModelService: (value) => ipcRenderer.invoke("ai-services:save-text", value),
  clearTextModelService: () => ipcRenderer.invoke("ai-services:clear-text"),
  saveRealtimeVoiceService: (value) => ipcRenderer.invoke("ai-services:save-realtime", value),
  clearRealtimeVoiceService: () => ipcRenderer.invoke("ai-services:clear-realtime"),
  startCompanionConversation: (value) => ipcRenderer.invoke("companion:start", value),
  stopCompanionConversation: () => ipcRenderer.invoke("companion:stop"),
  interruptCompanionConversation: () => ipcRenderer.invoke("companion:interrupt"),
  getCompanionConversationStatus: () => ipcRenderer.invoke("companion:get-status"),
  getCompanionPreferences: () => ipcRenderer.invoke("companion:get-preferences"),
  setCompanionPreferences: (value) => ipcRenderer.invoke("companion:set-preferences", value),
  getCompanionPersona: () => ipcRenderer.invoke("companion:get-persona"),
  setCompanionPersona: (value) => ipcRenderer.invoke("companion:set-persona", value),
  getCompanionIntent: () => ipcRenderer.invoke("companion:get-intent"),
  confirmCompanionIntent: (token) => ipcRenderer.invoke("companion:confirm-intent", token),
  rejectCompanionIntent: (token) => ipcRenderer.invoke("companion:reject-intent", token),
  setCompanionStartOptions: (value) => ipcRenderer.invoke("companion:set-start-options", value),
  testCompanionCallAction: () => ipcRenderer.invoke("companion:test-call-action"),
  onCompanionConversationEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("companion-conversation-event", handler); return () => ipcRenderer.removeListener("companion-conversation-event", handler); },
  setCompanionComputerAudioReady: (ready) => ipcRenderer.invoke("companion:set-computer-audio-ready", Boolean(ready)),
  sendCompanionComputerAudioEvent: (value) => ipcRenderer.send("companion:computer-audio-event", value),
  onCompanionComputerAudioCommand: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("companion-computer-audio-command", handler); return () => ipcRenderer.removeListener("companion-computer-audio-command", handler); },
  getMemoryStatus: () => ipcRenderer.invoke("memory:get-status"),
  listMemories: (value) => ipcRenderer.invoke("memory:list", value),
  setMemoryCandidateState: (value) => ipcRenderer.invoke("memory:set-candidate-state", value),
  updateMemoryCandidate: (value) => ipcRenderer.invoke("memory:update-candidate", value),
  prepareMemoryForget: (value) => ipcRenderer.invoke("memory:prepare-forget", value),
  confirmMemoryForget: (value) => ipcRenderer.invoke("memory:confirm-forget", value),
  exportReviewedMemories: () => ipcRenderer.invoke("memory:export-reviewed"),
  getKnowledgeBaseStatus: () => ipcRenderer.invoke("memory:get-knowledge-base-status"),
  chooseKnowledgeBaseLocation: () => ipcRenderer.invoke("memory:choose-knowledge-base"),
  generatePendingMemories: () => ipcRenderer.invoke("memory:generate-pending"),
  rebuildMemoryIndex: () => ipcRenderer.invoke("memory:rebuild-index"),
  searchMemoryIndex: (value) => ipcRenderer.invoke("memory:search-index", value),
  syncKnowledgeBase: () => ipcRenderer.invoke("memory:sync-knowledge-base"),
  transcribeBailian: (value) => ipcRenderer.invoke("bailian:transcribe", value),
  cancelBailian: (requestId) => ipcRenderer.invoke("bailian:cancel", requestId),
  organizeBailian: (value) => ipcRenderer.invoke("bailian:organize", value),
  editSelectedText: (value) => ipcRenderer.invoke("bailian:edit-selected-text", value),
  cancelBailianOrganizer: (requestId) => ipcRenderer.invoke("bailian:cancel-organize", requestId),
  startBailianRealtime: () => ipcRenderer.invoke("bailian:realtime-start"),
  appendBailianRealtime: (value) => ipcRenderer.invoke("bailian:realtime-append", value),
  finishBailianRealtime: (sessionId) => ipcRenderer.invoke("bailian:realtime-finish", sessionId),
  cancelBailianRealtime: (sessionId) => ipcRenderer.invoke("bailian:realtime-cancel", sessionId),
  onBailianRealtimeEvent: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("bailian-realtime-event", handler); return () => ipcRenderer.removeListener("bailian-realtime-event", handler); },
  onVoiceToggle: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("voice-toggle", handler); return () => ipcRenderer.removeListener("voice-toggle", handler); },
  onVoiceEditError: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("voice-edit-error", handler); return () => ipcRenderer.removeListener("voice-edit-error", handler); },
  onVoiceCancel: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("voice-cancel", handler); return () => ipcRenderer.removeListener("voice-cancel", handler); },
  onKeyDiagnostic: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("key-diagnostic", handler); return () => ipcRenderer.removeListener("key-diagnostic", handler); },
  onInputBridgeStatus: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("input-bridge-status", handler); return () => ipcRenderer.removeListener("input-bridge-status", handler); },
  onHostActionResult: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("host-action-result", handler); return () => ipcRenderer.removeListener("host-action-result", handler); },
  onAgentProviderState: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("agent-provider-state", handler); return () => ipcRenderer.removeListener("agent-provider-state", handler); },
  onCodexAgentState: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("codex-agent-state", handler); return () => ipcRenderer.removeListener("codex-agent-state", handler); },
  onNavigate: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("desktop-navigate", handler); return () => ipcRenderer.removeListener("desktop-navigate", handler); },
});
